version: "3"

networks:
 app-tier:
   driver: bridge

services:
#memgraph lab layer
  memgraph_lab:
    image: memgraph/memgraph-platform
    ports:
      - "7687:7687"
      - "7444:7444"
      - "3000:3000"
    networks:
      - app-tier

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - app-tier

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://localhost:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
<<<<<<< HEAD
      KAFKA_CREATE_TOPICS: "movies_info:1:1"
=======
      KAFKA_CREATE_TOPICS: "movietopic:1:1"
>>>>>>> 2ef97dd83c662887ad2229fa1869c44a2335d759
    networks:
      - app-tier